name: Ruby Gem (Self-Hosted, Secure)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build + Test + Publish
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Install system dependencies for OCR
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr poppler-utils imagemagick

      # 3️⃣ Install Ruby 2.6.0 (rbenv + ruby-build)
      - name: Install Ruby 2.6.0
        run: |
          if ! command -v ruby >/dev/null; then
            git clone https://github.com/rbenv/rbenv.git ~/.rbenv
            cd ~/.rbenv && src/configure && make -C src
            git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
            export PATH="$HOME/.rbenv/bin:$PATH"
            eval "$(rbenv init -)"
            rbenv install 2.6.0
            rbenv global 2.6.0
          fi
          ruby -v

      # 4️⃣ Install Bundler and dependencies
      - name: Install Bundler & Gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      # 5️⃣ Run tests
      - name: Run RSpec
        run: bundle exec rspec

      # 6️⃣ Build gem
      - name: Build gem
        run: gem build *.gemspec

      # 7️⃣ Publish to GitHub Packages (only repo owner)
      - name: Publish to GitHub Packages
        if: github.actor == github.repository_owner
        run: |
          mkdir -p $HOME/.gem
          echo "---" > $HOME/.gem/credentials
          echo ":github: $GITHUB_TOKEN" >> $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 8️⃣ Publish to RubyGems (only repo owner)
      - name: Publish to RubyGems
        if: github.actor == github.repository_owner
        run: |
          mkdir -p $HOME/.gem
          echo "---" > $HOME/.gem/credentials
          echo ":rubygems_api_key: $RUBYGEMS_AUTH_TOKEN" >> $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          gem push *.gem
        env:
          RUBYGEMS_AUTH_TOKEN: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
